---
- hosts: wordpress
  become: yes
  tasks:
  -  name: Install Postfix
     apt:
       name=postfix
       state=latest
     when:
       ansible_os_family == "Debian"

  -  name: Install ClamAV
     apt:
       name=clamav
       state=latest
     when:
       ansible_os_family == "Debian"

  -  name: Install Roundcube
     apt:
       name=roundcube
       state=latest
     when:
       ansible_os_family == "Debian"
