---
- hosts: all
  become: yes
  tasks:
  -  name: Install zabbix-agent
     apt:
        name=zabbix-agent
        state=latest
     when:
        ansible_os_family == "Debian"
     notify:
        zabbix-agent systemd


  -  name: Ansible replace string Server zabbix-agent
     replace:
           path: /etc/zabbix/zabbix_agentd.conf
           regexp: 'Server=127.0.0.1'
           replace: 'Server=84.201.131.34'


  -  name: Ansible replace string ServerActive zabbix-agent
     replace:
           path: /etc/zabbix/zabbix_agentd.conf
           regexp: 'ServerActive=127.0.0.1'
           replace: 'ServerActive=84.201.131.34'


  -  name: Ansible replace string Hostname zabbix-agent
     replace:
           path: /etc/zabbix/zabbix_agentd.conf
           regexp: '# Hostname='
           replace: 'Hostname=84.201.131.34'


  handlers:
  - name: zabbix-agent systemd
    systemd:
     name: zabbix-agent.service
     enabled: yes
     state: started
